package com.shavarushka.commands.interfaces;

public enum BotState {
    WAITING_FOR_CART_NAME,
    WAITING_FOR_CATEGORY_NAME,
    WAITING_FOR_USERNAME_TO_INVITE,
    CONFIRMING_CART_CREATION,
    CONFIRMING_CATEGORY_CREATION,
    CONFIRMING_CART_DELETION,
    CONFIRMING_PRODUCT_DELETION
}
