#!/bin/bash

JAR_NAME=tgbot-shopping-cart
PROJECT_ROOT="$HOME/.local/$JAR_NAME"
DATE=$(date +%Y-%m-%d)

get_bot_working_info() {
    ps aux | grep $JAR_NAME.jar
}

start_bot_in_background() {
    nohup java -jar "$PROJECT_ROOT/$JAR_NAME.jar" > "$PROJECT_ROOT/logs/bot-$DATE.log" 2>&1 &
}

execute_start() {
    mkdir -p "$PROJECT_ROOT/logs"
    start_bot_in_background
}

kill_bot_process() {
    bot_pid=$(pgrep -f "java -jar $PROJECT_ROOT/$JAR_NAME.jar")
    [ -n "$bot_pid" ] && kill $bot_pid
}

execute_stop() {
    kill_bot_process
}

command=$1
case "$command" in
    "start")
        execute_start
    ;;
    "status")
        get_bot_working_info
    ;;
    "stop")
        execute_stop
    ;;
    *)
        echo "Usage: $0 {start|status|stop}"
        exit 0
    ;;
esac
